import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { BarChart3, BellRing, CheckCircle2, Download, FileUp, FolderKanban, Mail, MessageSquareText, Save, ShieldCheck, Target, UserCircle, Users } from 'lucide-react';
import toast from 'react-hot-toast';
import { useAuth } from '../context/AuthContext.jsx';
import { api } from '../utils/api.js';
import Modal from '../components/Modal.jsx';

const featureCards = [
  { title: 'Team chat', text: 'Project chat endpoints and Socket.IO events are ready for live collaboration.', icon: MessageSquareText, tone: 'text-cyan-300 bg-cyan-500/10' },
  { title: 'Email notifications', text: 'SMTP variables enable password reset flows and reminder emails.', icon: BellRing, tone: 'text-fuchsia-300 bg-fuchsia-500/10' },
  { title: 'File uploads', text: 'Task attachments and avatar upload routes use Multer and the uploads folder.', icon: FileUp, tone: 'text-emerald-300 bg-emerald-500/10' }
];

export default function Profile() {
  const { user } = useAuth();
  const [form, setForm] = useState({ name: user?.name || '', title: user?.title || '', department: user?.department || '' });
  const [myTasks, setMyTasks] = useState([]);
  const [myProjects, setMyProjects] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showAllCompleted, setShowAllCompleted] = useState(false);
  const [showAllLedProjects, setShowAllLedProjects] = useState(false);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      setLoading(true);
      try {
        const [tasksRes, projectsRes] = await Promise.all([
          api('/tasks?assignee=me&limit=200'),
          api('/projects?limit=200')
        ]);
        if (cancelled) return;
        setMyTasks(tasksRes.items || []);
        setMyProjects(projectsRes.items || []);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const stats = useMemo(() => {
    const completedTasks = myTasks.filter((t) => t.status === 'Completed').length;
    const overdueTasks = myTasks.filter((t) => t.dueDate && new Date(t.dueDate) < new Date() && t.status !== 'Completed').length;
    const activeTasks = myTasks.length - completedTasks;
    const assignedProjects = myProjects.filter((p) => (p.members || []).some((m) => (m?._id || m) === user?._id));
    const leadProjects = myProjects.filter((p) => (p.manager?._id || p.manager) === user?._id);
    const completedProjects = assignedProjects.filter((p) => p.status === 'Completed').length;
    const readyApprovals = leadProjects.filter((p) => (p.progress || 0) === 100 && p.status !== 'Completed' && !p.archived).length;

    return {
      completedTasks,
      overdueTasks,
      activeTasks,
      assignedProjectsCount: assignedProjects.length,
      completedProjects,
      leadProjectsCount: leadProjects.length,
      readyApprovals
    };
  }, [myTasks, myProjects, user?._id]);

  const completedTasks = useMemo(() => myTasks.filter((t) => t.status === 'Completed'), [myTasks]);
  const ledProjects = useMemo(() => myProjects.filter((p) => (p.manager?._id || p.manager) === user?._id), [myProjects, user?._id]);

  const save = async (event) => {
    event.preventDefault();
    await api('/users/profile', { method: 'PATCH', body: JSON.stringify(form) });
    toast.success('Profile updated. Refresh to see header changes.');
  };

  const exportPdf = () => {
    const text = [
      'TaskFlow Project Report',
      `Generated by: ${user.name}`,
      `Generated at: ${new Date().toLocaleString()}`,
      '',
      'Includes dashboard summaries, project progress, task statuses, activity logs, notifications, and team collaboration notes.'
    ];
    const body = text.map((line, index) => `BT /F1 14 Tf 50 ${760 - index * 24} Td (${line.replace(/[()]/g, '')}) Tj ET`).join('\n');
    const pdf = `%PDF-1.4
1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj
2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj
3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj
4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj
5 0 obj << /Length ${body.length} >> stream
${body}
endstream endobj
xref
0 6
0000000000 65535 f 
trailer << /Root 1 0 R /Size 6 >>
startxref
0
%%EOF`;
    const url = URL.createObjectURL(new Blob([pdf], { type: 'application/pdf' }));
    const link = document.createElement('a');
    link.href = url;
    link.download = 'project-report.pdf';
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="grid gap-6 xl:grid-cols-[420px_1fr]">
      <motion.aside
        initial={{ opacity: 0, y: 18 }}
        animate={{ opacity: 1, y: 0 }}
        className="overflow-hidden rounded-[2rem] border border-white/10 bg-gradient-to-br from-blue-600/15 via-slate-900/85 to-fuchsia-600/15 p-5 shadow-2xl backdrop-blur-2xl sm:p-6"
      >
        <div className="flex items-center gap-4">
          <div className="grid h-20 w-20 place-items-center rounded-[1.75rem] bg-gradient-to-br from-blue-600 via-indigo-500 to-fuchsia-500 text-3xl font-black text-white shadow-lg shadow-blue-500/25 ring-1 ring-white/20">
            {user?.name?.[0] || 'U'}
          </div>
          <div className="min-w-0">
            <p className="text-xs font-black uppercase tracking-[0.22em] text-cyan-300">Account</p>
            <h1 className="mt-1 truncate text-2xl font-black text-white">{user?.name}</h1>
            <p className="mt-1 truncate text-sm font-semibold text-slate-400">{user?.email}</p>
          </div>
        </div>

        <div className="mt-6 grid gap-3">
          <div className="rounded-2xl border border-white/10 bg-white/[0.055] p-4">
            <p className="flex items-center gap-2 text-sm font-bold text-slate-300">
              <ShieldCheck size={16} className="text-emerald-300" />
              {user?.role || 'Member'} access
            </p>
          </div>
          <div className="rounded-2xl border border-white/10 bg-white/[0.055] p-4">
            <p className="flex items-center gap-2 text-sm font-bold text-slate-300">
              <Mail size={16} className="text-cyan-300" />
              {form.department || 'Product'} department
            </p>
          </div>
          <div className="rounded-2xl border border-white/10 bg-white/[0.055] p-4">
            <p className="flex items-center gap-2 text-sm font-bold text-slate-300">
              <Users size={16} className="text-fuchsia-300" />
              {form.title || 'Contributor'} title
            </p>
          </div>
        </div>
      </motion.aside>

      <div className="grid gap-6">
        <motion.section
          initial={{ opacity: 0, y: 18 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.03 }}
          className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"
        >
          {[
            { label: 'Assigned projects', value: stats.assignedProjectsCount, icon: FolderKanban, tone: 'from-blue-500 to-cyan-500' },
            { label: 'Completed tasks', value: stats.completedTasks, icon: CheckCircle2, tone: 'from-emerald-500 to-teal-500' },
            { label: 'Active tasks', value: stats.activeTasks, icon: Target, tone: 'from-violet-500 to-fuchsia-500' },
            { label: 'Overdue', value: stats.overdueTasks, icon: BarChart3, tone: 'from-rose-500 to-red-500' }
          ].map((card) => {
            const Icon = card.icon;
            return (
              <article key={card.label} className="card p-5">
                <div className={`mb-4 grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br ${card.tone} text-white shadow-lg shadow-black/10`}>
                  <Icon size={18} />
                </div>
                <p className="text-xs font-black uppercase tracking-[0.22em] text-slate-500">{card.label}</p>
                <p className="mt-2 text-3xl font-black text-white">{loading ? '—' : card.value}</p>
                {card.label === 'Assigned projects' && stats.leadProjectsCount > 0 && (
                  <p className="mt-2 text-xs font-semibold text-slate-500">
                    Leading {stats.leadProjectsCount} project{stats.leadProjectsCount === 1 ? '' : 's'}{stats.readyApprovals ? ` · ${stats.readyApprovals} ready approvals` : ''}
                  </p>
                )}
              </article>
            );
          })}
        </motion.section>

        <motion.form
          onSubmit={save}
          initial={{ opacity: 0, y: 18 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.06 }}
          className="card p-5 sm:p-6"
        >
          <div className="mb-5 flex items-center gap-3">
            <div className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-500/15 text-blue-300">
              <UserCircle size={22} />
            </div>
            <div>
              <p className="text-xs font-black uppercase tracking-[0.2em] text-slate-500">Settings</p>
              <h2 className="text-xl font-black text-white">Profile management</h2>
            </div>
          </div>
          <div className="grid gap-4 md:grid-cols-3">
            <input className="input" aria-label="Name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} />
            <input className="input" placeholder="Title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} />
            <input className="input" placeholder="Department" value={form.department} onChange={(e) => setForm({ ...form, department: e.target.value })} />
          </div>
          <button className="btn-primary mt-5 w-full sm:w-auto">
            <Save size={18} />
            Save profile
          </button>
        </motion.form>

        <motion.section
          initial={{ opacity: 0, y: 18 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="grid gap-4 lg:grid-cols-2"
        >
          <div className="card p-5 sm:p-6">
            <div className="mb-4 flex items-center gap-3">
              <div className="grid h-11 w-11 place-items-center rounded-2xl bg-emerald-500/12 text-emerald-200">
                <CheckCircle2 size={20} />
              </div>
              <div>
                <p className="text-xs font-black uppercase tracking-[0.2em] text-slate-500">Productivity</p>
                <h2 className="text-xl font-black text-white">My completed tasks</h2>
              </div>
            </div>
            <div className="grid gap-3">
              {completedTasks.slice(0, 6).length ? (
                completedTasks.slice(0, 6).map((task) => (
                    <div key={task._id} className="rounded-2xl border border-white/10 bg-white/[0.04] p-4">
                      <p className="truncate font-black text-white">{task.title}</p>
                      <p className="mt-1 truncate text-xs font-semibold text-slate-500">{task.project?.name || 'No project'}</p>
                    </div>
                  ))
              ) : (
                <div className="rounded-2xl border border-dashed border-white/10 bg-white/[0.03] p-6 text-sm font-semibold text-slate-500">
                  {loading ? 'Loading tasks…' : 'No completed tasks yet.'}
                </div>
              )}
            </div>
            {completedTasks.length > 6 && (
              <button type="button" onClick={() => setShowAllCompleted(true)} className="btn-secondary mt-4 w-full justify-center !py-2.5">
                See more
              </button>
            )}
          </div>

          <div className="card p-5 sm:p-6">
            <div className="mb-4 flex items-center gap-3">
              <div className="grid h-11 w-11 place-items-center rounded-2xl bg-amber-500/12 text-amber-200">
                <FolderKanban size={20} />
              </div>
              <div>
                <p className="text-xs font-black uppercase tracking-[0.2em] text-slate-500">Ownership</p>
                <h2 className="text-xl font-black text-white">Projects I lead</h2>
              </div>
            </div>
            <div className="grid gap-3">
              {ledProjects.slice(0, 6).length ? (
                ledProjects.slice(0, 6).map((project) => (
                    <div key={project._id} className="rounded-2xl border border-white/10 bg-white/[0.04] p-4">
                      <div className="flex items-start justify-between gap-3">
                        <div className="min-w-0">
                          <p className="truncate font-black text-white">{project.name}</p>
                          <p className="mt-1 text-xs font-semibold text-slate-500">
                            {project.status === 'Completed' ? 'Completed' : ((project.progress || 0) === 100 ? 'Ready for approval' : (project.status || 'Active'))}
                          </p>
                        </div>
                        <span className="pill bg-white/10 text-slate-200 text-xs">{project.progress || 0}%</span>
                      </div>
                      <div className="mt-3 h-2 rounded-full bg-white/10">
                        <div className="h-2 rounded-full bg-gradient-to-r from-amber-400 to-fuchsia-400" style={{ width: `${project.progress || 0}%` }} />
                      </div>
                    </div>
                  ))
              ) : (
                <div className="rounded-2xl border border-dashed border-white/10 bg-white/[0.03] p-6 text-sm font-semibold text-slate-500">
                  {loading ? 'Loading projects…' : 'No lead projects yet.'}
                </div>
              )}
            </div>
            {ledProjects.length > 6 && (
              <button type="button" onClick={() => setShowAllLedProjects(true)} className="btn-secondary mt-4 w-full justify-center !py-2.5">
                See more
              </button>
            )}
          </div>
        </motion.section>

        <motion.section
          initial={{ opacity: 0, y: 18 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.12 }}
          className="grid gap-4 md:grid-cols-3"
        >
          {featureCards.map(({ title, text, icon: Icon, tone }) => (
            <article key={title} className="card group p-5 transition duration-300 hover:-translate-y-1 hover:bg-white/[0.085]">
              <div className={`mb-4 grid h-11 w-11 place-items-center rounded-2xl ${tone}`}>
                <Icon size={20} />
              </div>
              <h3 className="font-black text-white">{title}</h3>
              <p className="mt-2 text-sm font-semibold leading-6 text-slate-400">{text}</p>
            </article>
          ))}
        </motion.section>

        <motion.section
          initial={{ opacity: 0, y: 18 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.18 }}
          className="premium-card flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"
        >
          <div>
            <p className="text-xs font-black uppercase tracking-[0.22em] text-cyan-300">Workspace export</p>
            <h2 className="mt-2 text-xl font-black text-white">Project report PDF</h2>
            <p className="mt-2 max-w-xl text-sm font-semibold leading-6 text-slate-400">
              Export a lightweight summary covering progress, task status, activity, notifications, and collaboration notes.
            </p>
          </div>
          <button onClick={exportPdf} className="btn-secondary w-full sm:w-auto">
            <Download size={18} />
            Export PDF
          </button>
        </motion.section>
      </div>

      <Modal
        open={showAllCompleted}
        onClose={() => setShowAllCompleted(false)}
        title="Completed tasks"
        description="A full list of tasks you've completed."
        size="lg"
      >
        <div className="grid max-h-[70vh] gap-3 overflow-auto pr-1 [scrollbar-width:thin]">
          {completedTasks.map((task) => (
            <div key={task._id} className="rounded-2xl border border-white/10 bg-white/[0.04] p-4">
              <p className="font-black text-white">{task.title}</p>
              <p className="mt-1 text-xs font-semibold text-slate-500">{task.project?.name || 'No project'}</p>
              {task.dueDate && <p className="mt-2 text-xs font-semibold text-slate-500">Due: {new Date(task.dueDate).toLocaleDateString()}</p>}
            </div>
          ))}
          {completedTasks.length === 0 && (
            <div className="rounded-2xl border border-dashed border-white/10 bg-white/[0.03] p-6 text-sm font-semibold text-slate-500">
              No completed tasks yet.
            </div>
          )}
        </div>
      </Modal>

      <Modal
        open={showAllLedProjects}
        onClose={() => setShowAllLedProjects(false)}
        title="Projects I lead"
        description="Projects where you're the Project Lead."
        size="lg"
      >
        <div className="grid max-h-[70vh] gap-3 overflow-auto pr-1 [scrollbar-width:thin]">
          {ledProjects.map((project) => (
            <div key={project._id} className="rounded-2xl border border-white/10 bg-white/[0.04] p-4">
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <p className="truncate font-black text-white">{project.name}</p>
                  <p className="mt-1 text-xs font-semibold text-slate-500">
                    {project.status === 'Completed' ? 'Completed' : ((project.progress || 0) === 100 ? 'Ready for approval' : (project.status || 'Active'))}
                  </p>
                </div>
                <span className="pill bg-white/10 text-slate-200 text-xs">{project.progress || 0}%</span>
              </div>
              <div className="mt-3 h-2 rounded-full bg-white/10">
                <div className="h-2 rounded-full bg-gradient-to-r from-amber-400 to-fuchsia-400" style={{ width: `${project.progress || 0}%` }} />
              </div>
            </div>
          ))}
          {ledProjects.length === 0 && (
            <div className="rounded-2xl border border-dashed border-white/10 bg-white/[0.03] p-6 text-sm font-semibold text-slate-500">
              No lead projects yet.
            </div>
          )}
        </div>
      </Modal>
    </motion.div>
  );
}
