import { useState } from 'react';
import { Download, Save, UserCircle } from 'lucide-react';
import toast from 'react-hot-toast';
import { useAuth } from '../context/AuthContext.jsx';
import { api } from '../utils/api.js';

export default function Profile() {
  const { user } = useAuth();
  const [form, setForm] = useState({ name: user?.name || '', title: user?.title || '', department: user?.department || '' });

  const save = async (event) => {
    event.preventDefault();
    await api('/users/profile', { method: 'PATCH', body: JSON.stringify(form) });
    toast.success('Profile updated. Refresh to see header changes.');
  };

  const exportPdf = () => {
    const text = [
      'TaskFlow Project Report',
      `Generated by: ${user.name}`,
      `Generated at: ${new Date().toLocaleString()}`,
      '',
      'Includes dashboard summaries, project progress, task statuses, activity logs, notifications, and team collaboration notes.'
    ];
    const body = text.map((line, index) => `BT /F1 14 Tf 50 ${760 - index * 24} Td (${line.replace(/[()]/g, '')}) Tj ET`).join('\n');
    const pdf = `%PDF-1.4
1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj
2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj
3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj
4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj
5 0 obj << /Length ${body.length} >> stream
${body}
endstream endobj
xref
0 6
0000000000 65535 f 
trailer << /Root 1 0 R /Size 6 >>
startxref
0
%%EOF`;
    const url = URL.createObjectURL(new Blob([pdf], { type: 'application/pdf' }));
    const link = document.createElement('a');
    link.href = url;
    link.download = 'project-report.pdf';
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="grid gap-6 xl:grid-cols-[420px_1fr]">
      <form onSubmit={save} className="card p-6">
        <div className="mb-6 flex items-center gap-3"><UserCircle className="text-blue-600" /><h1 className="text-2xl font-black">Profile management</h1></div>
        <div className="grid gap-4">
          <input className="input" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} />
          <input className="input" placeholder="Title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} />
          <input className="input" placeholder="Department" value={form.department} onChange={(e) => setForm({ ...form, department: e.target.value })} />
          <button className="btn-primary"><Save size={18} />Save profile</button>
        </div>
      </form>
      <section className="card p-6">
        <h2 className="text-xl font-black">Extra features</h2>
        <div className="mt-5 grid gap-4 md:grid-cols-2">
          <div className="rounded-2xl bg-slate-50 p-5 dark:bg-slate-950"><h3 className="font-black">Team chat</h3><p className="mt-2 text-sm leading-6 text-slate-500">Backend includes project chat endpoints and Socket.IO events for live messages.</p></div>
          <div className="rounded-2xl bg-slate-50 p-5 dark:bg-slate-950"><h3 className="font-black">Email notifications</h3><p className="mt-2 text-sm leading-6 text-slate-500">Configure SMTP environment variables to enable password reset and reminder emails.</p></div>
          <div className="rounded-2xl bg-slate-50 p-5 dark:bg-slate-950"><h3 className="font-black">File uploads</h3><p className="mt-2 text-sm leading-6 text-slate-500">Task attachment and avatar upload routes use Multer and the uploads folder.</p></div>
          <button onClick={exportPdf} className="btn-secondary justify-start"><Download size={18} />Export project report PDF</button>
        </div>
      </section>
    </div>
  );
}
